import Foundation
import Testing
@testable import millio

struct MainLocalizationTests {
    @Test("Main screen strings are localized for Simplified Chinese")
    func mainScreenStringsInSimplifiedChinese() {
        let locale = Locale(identifier: "zh-Hans")

        #expect(AppLocalization.string("main.history.accessibility", locale: locale) == "交易历史")
        #expect(AppLocalization.string("main.quick_action.history", locale: locale) == "历史")
        #expect(AppLocalization.string("main.quick_action.expense", locale: locale) == "支出")
        #expect(AppLocalization.string("main.quick_action.income", locale: locale) == "收入")
        #expect(AppLocalization.string("main.layout.classic", locale: locale) == "经典")
        #expect(AppLocalization.string("main.layout.focus", locale: locale) == "聚焦")
        #expect(AppLocalization.string("main.layout.switch.accessibility", locale: locale) == "切换主屏幕布局")
        #expect(AppLocalization.string("main.focus.eyebrow", locale: locale) == "控制中心")
        #expect(AppLocalization.string("main.focus.title", locale: locale) == "一屏进入核心操作")
        #expect(AppLocalization.string("main.focus.subtitle", locale: locale) == "先完成关键动作，再进入各个模块。")
        #expect(AppLocalization.string("main.dashboard.edit.title", locale: locale) == "编辑面板")
        #expect(AppLocalization.string("main.dashboard.edit.subtitle", locale: locale) == "重新排序部件，并决定哪些内容显示在主屏幕上。")
        #expect(AppLocalization.string("main.dashboard.edit.close", locale: locale) == "关闭")
        #expect(AppLocalization.string("main.dashboard.edit.widgets.section", locale: locale) == "部件")
        #expect(AppLocalization.string("main.dashboard.edit.open", locale: locale) == "编辑")
        #expect(AppLocalization.string("main.dashboard.widget.quick_actions.title", locale: locale) == "快速操作")
        #expect(AppLocalization.string("main.dashboard.widget.quick_actions.subtitle", locale: locale) == "最常用的动作要在一秒内可达。")
        #expect(AppLocalization.string("main.dashboard.widget.finances.title", locale: locale) == "财务总览")
        #expect(AppLocalization.string("main.dashboard.widget.finances.subtitle", locale: locale) == "总资产、结构和入口都应该在这里。")
        #expect(AppLocalization.string("main.dashboard.widget.finances.add_product", locale: locale) == "添加产品")
        #expect(AppLocalization.string("main.dashboard.widget.finances.open", locale: locale) == "打开财务")
        #expect(AppLocalization.string("main.dashboard.widget.finances.empty", locale: locale) == "添加第一个产品后，这里会出现你的资产结构。")
        #expect(AppLocalization.string("main.dashboard.widget.finances.products_count", locale: locale) == "%lld 个产品")
        #expect(AppLocalization.string("main.dashboard.widget.finances.segment.cards", locale: locale) == "账户")
        #expect(AppLocalization.string("main.dashboard.widget.finances.segment.investments", locale: locale) == "投资")
        #expect(AppLocalization.string("main.dashboard.widget.finances.segment.liabilities", locale: locale) == "负债")
        #expect(AppLocalization.string("main.dashboard.widget.converter.title", locale: locale) == "汇率快捷方式")
        #expect(AppLocalization.string("main.dashboard.widget.converter.subtitle", locale: locale) == "保留最常用的货币对，直接进入转换。")
        #expect(AppLocalization.string("main.dashboard.widget.services.title", locale: locale) == "服务")
        #expect(AppLocalization.string("main.dashboard.widget.services.subtitle", locale: locale) == "把主要模块放在眼前，顺序由你决定。")
        #expect(AppLocalization.string("main.services.section.title", locale: locale) == "服务")
        #expect(AppLocalization.string("main.services.reorder_hint", locale: locale) == "长按并拖动卡片来自定义顺序")
        #expect(AppLocalization.string("main.service.finances", locale: locale) == "资产")
        #expect(AppLocalization.string("main.service.courses", locale: locale) == "汇率")
        #expect(AppLocalization.string("main.service.cashback", locale: locale) == "返现")
        #expect(AppLocalization.string("main.service.cashflow", locale: locale) == "现金流")
        #expect(AppLocalization.string("main.quick_setup.banner.title", locale: locale) == "快速设置")
        #expect(AppLocalization.string("main.quick_setup.banner.subtitle", locale: locale) == "1 分钟完成语言、货币、分类和产品设置")
        #expect(AppLocalization.string("main.quick_setup.banner.open", locale: locale) == "打开")
    }
}
